# Generated by Django 5.2.7 on 2025-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.JSONField(blank=True, null=True)),
                ('memory', models.JSONField(blank=True, null=True)),
                ('price', models.CharField(max_length=255)),
                ('photo', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(max_length=255)),
                ('fb', models.CharField(max_length=255)),
                ('characteristics', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
