# Generated by Django 5.2.7 on 2025-10-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_selenium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='fb',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.CharField(),
        ),
    ]
